# Generated by Django 6.0 on 2026-01-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=100, unique=True)),
                ('police_station', models.CharField(max_length=200)),
                ('incident_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accused', 'Accused'), ('wanted', 'Wanted'), ('arrested', 'Arrested')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='case_persons/')),
                ('address', models.TextField(blank=True)),
                ('taluka', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('bank_details', models.TextField(blank=True)),
                ('family_details', models.TextField(blank=True)),
                ('urls', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='cases.case')),
            ],
        ),
    ]
