# Generated by Django 6.0 on 2026-01-06 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='district',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='family_details',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='state',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='urls',
        ),
        migrations.AddField(
            model_name='caseperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='status',
            field=models.CharField(choices=[('ACCUSED', 'Accused'), ('WANTED', 'Wanted'), ('ARRESTED', 'Arrested')], default='ACCUSED', max_length=20),
        ),
    ]
