# Generated by Django 6.0 on 2026-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_caseperson_address_remove_caseperson_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseperson',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='family_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='mobile_numbers',
            field=models.TextField(blank=True, help_text='Comma separated mobile numbers'),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='case_person/photos/'),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='taluka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caseperson',
            name='urls',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='fir_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='status',
            field=models.CharField(choices=[('ACCUSED', 'Accused'), ('WANTED', 'Wanted'), ('ARRESTED', 'Arrested')], max_length=20),
        ),
    ]
