# Generated by Django 6.0 on 2026-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseperson_address_caseperson_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseperson',
            name='documents',
            field=models.FileField(blank=True, help_text='Upload PDF / image / document', null=True, upload_to='case_person/documents/'),
        ),
    ]
