# Generated by Django 6.0 on 2026-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NastaFarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Accused', 'Accused'), ('Wanted', 'Wanted'), ('Arrested', 'Arrested')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nastafarta/photos/')),
                ('address', models.TextField(blank=True)),
                ('taluka', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('bank_details', models.TextField(blank=True)),
                ('family_details', models.TextField(blank=True)),
                ('urls', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nasta Farta Case',
                'verbose_name_plural': 'Nasta Farta Cases',
            },
        ),
    ]
