# Generated by Django 6.0 on 2026-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nastafarta',
            options={},
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='mobile_numbers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='status',
            field=models.CharField(choices=[('ACCUSED', 'Accused'), ('WANTED', 'Wanted'), ('ARRESTED', 'Arrested')], max_length=20),
        ),
    ]
