# Generated by Django 6.0 on 2026-01-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_nastafarta_options_nastafarta_mobile_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIRCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='age',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='state',
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='family_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='mobile_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons/'),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='status',
            field=models.CharField(choices=[('ARRESTED', 'Arrested'), ('WANTED', 'Wanted'), ('ACCUSED', 'Accused')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ARRESTED', 'Arrested'), ('WANTED', 'Wanted'), ('ACCUSED', 'Accused')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('family_details', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='case_persons/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fircase')),
            ],
        ),
    ]
