# Generated by Django 6.0 on 2026-01-08 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fircase_remove_nastafarta_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='family_details',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='mobile_numbers',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='family_details',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='mobile_numbers',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='nastafarta',
            name='urls',
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='taluka',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
