# Generated by Django 6.0 on 2026-01-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_caseperson_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fircase',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='accounts.fircase'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='status',
            field=models.CharField(choices=[('ARVALLI', 'Arvalli'), ('GUJARAT_STATE', 'Gujarat State'), ('OUTSIDE_GUJARAT', 'Outside Gujarat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='status',
            field=models.CharField(choices=[('ARVALLI', 'Arvalli'), ('GUJARAT_STATE', 'Gujarat State'), ('OUTSIDE_GUJARAT', 'Outside Gujarat')], max_length=30),
        ),
    ]
