# Generated by Django 6.0 on 2026-01-08 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_fircase_created_at_alter_caseperson_case_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nastafarta',
            options={'ordering': ['-id'], 'verbose_name': 'Nasta Farta', 'verbose_name_plural': 'Nasta Fartas'},
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='family_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='other_cases',
            field=models.TextField(blank=True, help_text='Reference to other FIRs / cases (text only)', null=True),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='phone_numbers',
            field=models.TextField(blank=True, help_text='Comma separated phone numbers', null=True),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='nasta_farta/photos/'),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nastafarta',
            name='urls',
            field=models.TextField(blank=True, help_text='Any related URLs / links', null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='status',
            field=models.CharField(choices=[('ARVALLI', 'Arvalli District'), ('GUJARATSTATE', 'Other District (Gujarat State)'), ('OUTSIDEGUJARAT', 'Outside Gujarat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nastafarta',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CasePerson',
        ),
        migrations.DeleteModel(
            name='FIRCase',
        ),
    ]
